"""Add quantity field to bookings table

Revision ID: 054dcefe2802
Revises: d5f569f04e37
Create Date: 2025-07-27 14:26:12.629483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054dcefe2802'
down_revision = 'd5f569f04e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
