"""feat: image base64

Revision ID: 950629d98334
Revises: a082c8c16a75
Create Date: 2025-07-24 19:40:55.346565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950629d98334'
down_revision = 'a082c8c16a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_base64', sa.Text(), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('image_base64')

    # ### end Alembic commands ###
