"""Update Item model for outfit rental

Revision ID: cdce7bd82128
Revises: ff3326806604
Create Date: 2025-07-21 22:04:58.600881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdce7bd82128'
down_revision = 'ff3326806604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', 'ONE_SIZE', name='size'), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.Enum('MENS', 'WOMENS', 'UNISEX', 'KIDS', name='gender'), nullable=False))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('DRESS', 'TOP', 'BOTTOM', 'OUTERWEAR', 'SHOES', 'ACCESSORY', 'JEWELRY', 'BAG', 'FORMAL_WEAR', 'COSTUME', 'OTHER', name='itemtype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('DRESS', 'TOP', 'BOTTOM', 'OUTERWEAR', 'SHOES', 'ACCESSORY', 'JEWELRY', 'BAG', 'FORMAL_WEAR', 'COSTUME', 'OTHER', name='itemtype'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('color')
        batch_op.drop_column('brand')
        batch_op.drop_column('gender')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
